version: '3.8'
services:
  php-apache-environment:
    container_name: myPHProject
    # image: bogdan123b/project-lab4-php-apache-environment
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8000:80
  db:
    container_name: db
    image: bogdan123b/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: MY_DATABASE
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
        - "9906:3306"
  phpmyadmin:
    image: bogdan123b/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db